[package]
name = "lofar-h5parm-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
hdf5 = "0.8.1"
ndarray = "0.15.6"
num-complex = "0.4.4"
