[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "lofar-h5parm-rs"
requires-python = ">3.8"

[tool.maturin]
module-name = "lofar_h5parm"

[tool.cargo]
cargo-extra-args = "--features extension-module"
